### ISSUE TITLE
Cannot select shipping method in Apple Pay payment sheet

### ISSUE THREAD

**Issue by pignion** [Adyen/adyen-magento2-express-checkout#106]
**Describe the bug**
When using Apple Pay from the shopping cart, I cannot select a shipping method, even when Magento provides multiple shipping methods. The first shipping method provided by Magento is automatically chosen.

**To Reproduce**
1. As a guest user, add an item to the cart
2. Go to the shopping cart
3. Click the Apple Pay button
4. In the payment sheet, select a shipping address that will return multiple shipping methods from Magento

**Expected behavior**

- I can select which shipping method I want to use. 
- If I've already selected a shipping method in Magento, the one I selected should be selected in the Apple Pay payment sheet, not simply the first one.

**Actual behavior**

- No shipping methods are displayed, and first shipping method is chosen.
- I cannot change shipping method from the payment sheet.
- If I customer selects a shipping method in Magento, then initiate an Apple Pay session from the cart; the selected shipping method is changed to the first one returned by Magento.

**Screenshots**

<img width="1728" alt="Screenshot 2024-08-28 at 12 19 52 PM" src="https://github.com/user-attachments/assets/5a2a38dc-5149-4df1-98c8-72880ec03745">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - Browser: Safari

**Adyen Versions**

- adyen/adyen-magento2-expresscheckout: 2.1.0
- adyen/module-payment: 9.7.2

**Additional context**
The `ApplePaySession`'s `completeShippingContactSelection` should be called with all available shipping methods, which will cause them to show up as options on the payment sheet, according to the [Apple Documentation
](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778008-completeshippingcontactselection)

When I step through `button.js` and get to [the point where the shipping methods are retrieved from Magento,](https://github.com/Adyen/adyen-magento2-express-checkout/blob/main/view/frontend/web/js/applepay/button.js#L313) I can see multiple shipping methods returned, but they seem to be being discarded.

I can see pretty clearly [here](https://github.com/Adyen/adyen-magento2-express-checkout/blob/main/view/frontend/web/js/applepay/button.js#L359) where Adyen's Express Payment javascript is selecting the first available method rather than checking to see what shipping method has been selected in Magento:

**Comment by pignion** [comment]
Additional Information:
I've confirmed that when I downgrade to 2.0.0, I can see shipping methods, so this appears to be a regression in the latest version.

**Comment by candemiralp** [comment]
Hello @pignion,

Thank you for reporting this issue in details. As I see, @maxparkergene has already created a pull request for this bug. We will review and merge the fix soon.

Best Regards,
Can
