### ISSUE TITLE
[ECP-9533] Observer adyen_quote_submit overrides original Observer from adyen-magento2 module

### ISSUE THREAD

**Issue by sophie-mulard** [Adyen/adyen-magento2-express-checkout#131]
**Describe the bug**
Since version 2.2.0, you added the following observer: 

`    <event name="sales_model_service_quote_submit_success">
        <observer name="adyen_quote_submit" instance="Adyen\ExpressCheckout\Observer\SubmitQuoteObserver" />
    </event>`

However, in the adyen/adyen-magento2 module, there is already an observer, for the same event, with the same name "adyen_quote_submit": 
https://github.com/Adyen/adyen-magento2/blob/main/etc/events.xml#L60

`    <event name="sales_model_service_quote_submit_success">
        <observer name="adyen_quote_submit" instance="Adyen\Payment\Observer\SubmitQuoteObserver" />
    </event>`

As a result, the original observer Adyen\Payment\Observer\SubmitQuoteObserver is not called anymore.
Which means that quotes with payment requiring further actions are not kept active anymore (https://github.com/Adyen/adyen-magento2/blob/main/Observer/SubmitQuoteObserver.php#L69)

Could you please rename the observer in the express checkout module so that both observers can be triggered?

Thanks

**Expected behavior**
Both observers should be executed / Quote should remain active after creating the order if payment requires further action.

**Comment by candemiralp** [comment]
Hello @sophie-mulard,

Thank you for reporting this issue. We have created a ticket and this inconvenience will be solved soon.

Best Regards,
Can
